server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/usermanager}
    username: ${DBMS_NAME:root}
    password: ${DBMS_PASS:1111}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

#  elasticsearch:
#    uris: http://localhost:9200
#
#  data:
#    redis:
#      host: localhost
#      port: 6379

#jwt:
#    signerkey: "LDzDIQeFNWXeWjG/yQ3yQz0cNJY2QAx08t5vyu7/E1ZaYZNsaSzaQBQ/nhWH591f"
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.authentication: DEBUG

#swagger
open:
  api:
    title: API document
    version: v1.0.0
    description: Mo ta API
    serverUrl: /api/v1
    serverName: Local test
